twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '_form/form_layout.html.twig'
    globals:
        site_name: Maintainerati Bikeshed
        site_tagline: ~
